variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-GCC
  - build-Clang
  - test
  - valgrind
  - coverage
  - quality
  - deploy

include:
  - "/.gitlab/ci/build-freertos.yml"
  - "/.gitlab/ci/build-linux.yml"
  - "/.gitlab/ci/coverage-linux.yml"
  - "/.gitlab/ci/deploy.yml"
  - "/.gitlab/ci/quality.yml"
  - "/.gitlab/ci/test-linux.yml"
  - "/.gitlab/ci/valgrind-linux.yml"
